--- #YAML:1.0
name:               Device-Gsm
version:            1.58
abstract:           Perl extension to interface GSM phones / modems
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Device::Modem:       1.47
    Device::SerialPort:  0
    Test::More:          0
resources:
    bugtracker:  mailto:bug-device-gsm@rt.cpan.org
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/cosimo/perl5-device-gsm.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
