--- #YAML:1.0
name:                Device-Gsm
version:             1.47
abstract:            Perl extension to interface GSM phones / modems
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Device::Modem:                 1.47
    Device::SerialPort:            0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Cosimo Streppone <cosimo@cpan.org>
